import { icons } from "./icon";

export const tabs = [
  { name: "index", title: "Home", icon: icons.home },
  { name: "subscriptions", title: "Subscriptions", icon: icons.wallet },
  { name: "insights", title: "Insights", icon: icons.activity },
  { name: "settings", title: "Settings", icon: icons.settings },
];

export const HOME_USER = {
  name: "Michael Theo",
};

export const HOME_BALANCE = {
  ammount: 128.45,
  currency: "USD",
  nextRenewalDatte: "2026-08-19T00:00:00Z",
};

export const HOME_SUBSCRIPTIONS: Subscription[] = [
  {
    id: "github-pro",
    icon: icons.github,
    name: "Github Pro",
    price: 4.99,
    billingCycle: "month",
    plan: "Developer Plan",
    category: "Developer Tools",
    paymentMethod: "Mastercard **** 1234",
    status: "active",
    billing: "Monthly",
    renewalDate: "2026-08-19T00:00:00Z",
  },
  {
    id: "canva-pro",
    icon: icons.canva,
    name: "Canva Pro",
    price: 12.99,
    billingCycle: "month",
    plan: "Pro Plan",
    category: "Design",
    paymentMethod: "Visa **** 5678",
    status: "active",
    billing: "Monthly",
    renewalDate: "2026-07-02T00:00:00Z",
  },
  {
    id: "claude-pro",
    icon: icons.claude,
    name: "Claude Pro",
    price: 20.0,
    billingCycle: "month",
    plan: "Pro Plan",
    category: "AI Assistant",
    paymentMethod: "Mastercard **** 1234",
    status: "active",
    billing: "Monthly",
    renewalDate: "2026-06-28T00:00:00Z",
  },
  {
    id: "dropbox-plus",
    icon: icons.dropbox,
    name: "Dropbox Plus",
    price: 11.99,
    billingCycle: "month",
    plan: "Plus Plan",
    category: "Cloud Storage",
    paymentMethod: "PayPal",
    status: "active",
    billing: "Monthly",
    renewalDate: "2026-07-15T00:00:00Z",
  },
  {
    id: "figma-professional",
    icon: icons.figma,
    name: "Figma Professional",
    price: 15.0,
    billingCycle: "month",
    plan: "Professional Plan",
    category: "Design",
    paymentMethod: "Visa **** 5678",
    status: "active",
    billing: "Monthly",
    renewalDate: "2026-08-05T00:00:00Z",
  },
  {
    id: "medium-membership",
    icon: icons.medium,
    name: "Medium Membership",
    price: 5.0,
    billingCycle: "month",
    plan: "Member Plan",
    category: "Reading",
    paymentMethod: "Mastercard **** 1234",
    status: "active",
    billing: "Monthly",
    renewalDate: "2026-07-09T00:00:00Z",
  },
  {
    id: "openai-plus",
    icon: icons.openai,
    name: "ChatGPT Plus",
    price: 20.0,
    billingCycle: "month",
    plan: "Plus Plan",
    category: "AI Assistant",
    paymentMethod: "Mastercard **** 1234",
    status: "active",
    billing: "Monthly",
    renewalDate: "2026-06-30T00:00:00Z",
  },
];

export const UPCOMING_SUBSCRIPTIONS: UpcomingSubscription[] = [
  {
    id: "spotify-premium",
    icon: icons.spotify,
    name: "Spotify Premium",
    price: 10.99,
    currency: "USD",
    daysLeft: 3,
  },
  {
    id: "notion-plus",
    icon: icons.notion,
    name: "Notion Plus",
    price: 10.0,
    currency: "USD",
    daysLeft: 8,
  },
  {
    id: "adobe-creative-cloud",
    icon: icons.adobe,
    name: "Adobe Creative Cloud",
    price: 59.99,
    currency: "USD",
    daysLeft: 14,
  },
];
